### ISSUE TITLE
eror when start

### ISSUE THREAD

**Issue by pengengantibaju** [Tomato6966/light-music-bot#4]
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/runner/light-music-bot/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/light-music-bot/node_modules/discord.js/src/index.js
- /home/runner/light-music-bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/light-music-bot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/light-music-bot/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/light-music-bot/node_modules/discord.js/src/index.js',
    '/home/runner/light-music-bot/index.js'

**Comment by Shadeslayer10** [comment]
Update to node version `16.6.0` or higher.
